//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistryEntities : DbContext
    {
        public RegistryEntities()
            : base("name=RegistryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Professor> Professors { get; set; }
        public virtual DbSet<Subjet> Subjets { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_subjet> Student_subjet { get; set; }
        public virtual DbSet<Day> Days { get; set; }
    }
}
