//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; 

    public partial class Professor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professor()
        {
            this.Subjets = new HashSet<Subjet>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = "Name Professos is Required")] 
        [Display(Name ="Name")]
        public string name { get; set; }


        [Required(ErrorMessage = "Last Name Professos is Required")]
        [Display(Name = "Last Name")]
        public string last_name { get; set; }

        [Required(ErrorMessage = "DNI Professos is Required")]
        [Display(Name = "DNI")]
        public string dni { get; set; }


      
        [Display(Name = "Activity")]
        public bool activity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subjet> Subjets { get; set; }
    }
}
