//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Subjet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subjet()
        {
            this.Student_subjet = new HashSet<Student_subjet>();
        }
    
        public int id { get; set; }

        [Required(ErrorMessage = " Name is Required")]
        [Display(Name = "Name")]
        public string name { get; set; }

        [Required(ErrorMessage = " Name is Required")]
        [Display(Name = "Description")]
        public string description { get; set; }

        [Required(ErrorMessage = " Start Time is Required")]
        [Display(Name = "Start time")]
        public System.DateTime start_time { get; set; }

        [Required(ErrorMessage = " End Time is Required")]
        [Display(Name = "End time")]
        public System.DateTime end_time { get; set; }

        [Required(ErrorMessage = " End Time is Required")]
        [Display(Name = "Professor")]
        public int id_profesor { get; set; }

        [Required(ErrorMessage = " Vacancies is Required")]
        [Display(Name = "Vacancies")]
        [Range(0,30,ErrorMessage ="Out range 0-30")]
        public int vacancies { get; set; }

        [Required(ErrorMessage = " Day is Required")]
        [Display(Name = "Day")]
        public int id_day { get; set; }
    
        public virtual Professor Professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_subjet> Student_subjet { get; set; }
        public virtual Day Day { get; set; }
    }
}
